DROP TABLE IF EXISTS Documento;

DROP TABLE IF EXISTS Processo_Sei;

DROP TABLE IF EXISTS Atualizacao;

DROP TABLE IF EXISTS Correspondente;

DROP TABLE IF EXISTS Controle_Demanda;

DROP TABLE IF EXISTS Demanda;

DROP TABLE IF EXISTS Atividade;

DROP TABLE IF EXISTS Localizacao;

DROP TABLE IF EXISTS Sublocalidade;

DROP TABLE IF EXISTS Tipo;

DROP TABLE IF EXISTS Obj_Res_Cha;

DROP TABLE IF EXISTS Usuario;

DROP TABLE IF EXISTS Agente;

DROP TABLE IF EXISTS Entidade_Externa;

DROP TABLE IF EXISTS Setor;

DROP TABLE IF EXISTS Acesso_Diario;